kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  podSubnet: "{{pod_subnet}}"
  serviceSubnet: "{{service_subnet}}"
featureGates:
  EndpointSliceProxying: true
nodes:
  - role: control-plane
