kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  podSubnet: "{{pod_subnet}}"
  serviceSubnet: "{{service_subnet}}"
featureGates:
  EndpointSliceProxying: true
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 31030
      hostPort: 5000
      listenAddress: "{{host_ipaddress}}"
    - containerPort: 31080
      hostPort: 6000
      listenAddress: "{{host_ipaddress}}"
    extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
